// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN6_VCghR08rM0Y4n7hLO0UufAMUcomHU',
    appId: '1:478631718078:web:37882ad2876336d88ac2ef',
    messagingSenderId: '478631718078',
    projectId: 'todo-app-efrei',
    authDomain: 'todo-app-efrei.firebaseapp.com',
    storageBucket: 'todo-app-efrei.firebasestorage.app',
    measurementId: 'G-8TCX6CKNJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIYR8ck590EfCOwXPsJI7vxqxiQACOJQY',
    appId: '1:478631718078:android:1247d7a8a61af2b68ac2ef',
    messagingSenderId: '478631718078',
    projectId: 'todo-app-efrei',
    storageBucket: 'todo-app-efrei.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxqiuzGjhpRKrNro1EdIjPlk1m05vCSe4',
    appId: '1:478631718078:ios:5619b20bd6c282d28ac2ef',
    messagingSenderId: '478631718078',
    projectId: 'todo-app-efrei',
    storageBucket: 'todo-app-efrei.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxqiuzGjhpRKrNro1EdIjPlk1m05vCSe4',
    appId: '1:478631718078:ios:5619b20bd6c282d28ac2ef',
    messagingSenderId: '478631718078',
    projectId: 'todo-app-efrei',
    storageBucket: 'todo-app-efrei.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN6_VCghR08rM0Y4n7hLO0UufAMUcomHU',
    appId: '1:478631718078:web:58d612f29f9637488ac2ef',
    messagingSenderId: '478631718078',
    projectId: 'todo-app-efrei',
    authDomain: 'todo-app-efrei.firebaseapp.com',
    storageBucket: 'todo-app-efrei.firebasestorage.app',
    measurementId: 'G-K0DNY431TL',
  );
}
