// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0DBXXs9W5lja5PV6wlacehWoV6X-qSEg',
    appId: '1:580524309480:web:2ef6f04355978b445d425d',
    messagingSenderId: '580524309480',
    projectId: 'efrei-flutter-30437',
    authDomain: 'efrei-flutter-30437.firebaseapp.com',
    storageBucket: 'efrei-flutter-30437.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0DBXXs9W5lja5PV6wlacehWoV6X-qSEg',
    appId: '1:580524309480:android:2ef6f04355978b445d425d',
    messagingSenderId: '580524309480',
    projectId: 'efrei-flutter-30437',
    storageBucket: 'efrei-flutter-30437.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0DBXXs9W5lja5PV6wlacehWoV6X-qSEg',
    appId: '1:580524309480:ios:2ef6f04355978b445d425d',
    messagingSenderId: '580524309480',
    projectId: 'efrei-flutter-30437',
    storageBucket: 'efrei-flutter-30437.firebasestorage.app',
    iosClientId: '580524309480-iosclient.apps.googleusercontent.com',
    iosBundleId: 'com.example.efreiTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0DBXXs9W5lja5PV6wlacehWoV6X-qSEg',
    appId: '1:580524309480:ios:2ef6f04355978b445d425d',
    messagingSenderId: '580524309480',
    projectId: 'efrei-flutter-30437',
    storageBucket: 'efrei-flutter-30437.firebasestorage.app',
    iosClientId: '580524309480-macosclient.apps.googleusercontent.com',
    iosBundleId: 'com.example.efreiTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0DBXXs9W5lja5PV6wlacehWoV6X-qSEg',
    appId: '1:580524309480:web:2ef6f04355978b445d425d',
    messagingSenderId: '580524309480',
    projectId: 'efrei-flutter-30437',
    storageBucket: 'efrei-flutter-30437.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC0DBXXs9W5lja5PV6wlacehWoV6X-qSEg',
    appId: '1:580524309480:web:2ef6f04355978b445d425d',
    messagingSenderId: '580524309480',
    projectId: 'efrei-flutter-30437',
    storageBucket: 'efrei-flutter-30437.firebasestorage.app',
  );
}